apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  namespace: financeiro
spec:
  replicas: 1
  selector:
    matchLabels: { app: ingestion }
  template:
    metadata:
      labels: { app: ingestion }
    spec:
      containers:
        - name: ingestion
          image: local/ingestion:ci
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: postgres://app:app@postgres.financeiro.svc.cluster.local:5432/financeiro
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion
  namespace: financeiro
spec:
  selector: { app: ingestion }
  ports:
    - port: 8080
      targetPort: 8080
